### ISSUE TITLE
Crash at launch - missing libgdx.so

### ISSUE THREAD

**Issue by czarkoff** [trolley813/OpenFool#45]
I have installed 3.0 on my Xiaomi Redmi Note 8 Pro (Android Pie), and I get a crash at startup, immediately after the app rotates the screen to landscape.

```
java.lang.ExceptionInInitializerError
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2895)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3114)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6831)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx' for target: Linux, 32-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:125)
	at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:33)
	at com.badlogic.gdx.backends.android.AndroidApplication.<clinit>(AndroidApplication.java:60)
	... 15 more
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ru.hyst329.openfool-5fmrYz3syYdWZnAHMfFQQQ==/base.apk"],nativeLibraryDirectories=[/data/app/ru.hyst329.openfool-5fmrYz3syYdWZnAHMfFQQQ==/lib/arm64, /system/lib64]]] couldn't find "libgdx.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
	at java.lang.System.loadLibrary(System.java:1669)
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:119)
	... 17 more

```

**Comment by trolley813** [comment]
Thank you for the issue! Which version have you installed, the APK from GitHub Releases or one from F-Droid?

**Comment by ildar** [comment]
F-Droid

**Comment by czarkoff** [comment]
@trolley813 I tried both. This issue manifests itself only on F-Droid version. The build from github release is OK.

**Comment by trolley813** [comment]
@czarkoff the reason is probably in F-Droid build system itself, since the app didn't get built right after the release

**Comment by ptalus** [comment]
I got the same error using Android Studio 3.6.3 and the source code from the github. The building process is finished successfully but the error occurred when the app is started in emulator. At the same time the source from v0.2.9 runs successfully.

**Comment by AdityaMH** [comment]
> Which version have you installed, the APK from GitHub Releases or one from F-Droid?

I can't find apk files update on github (on releases assets or anywhere).
